### ISSUE TITLE
Power BI visuals interactions not working; errors when setting multiple "Rows" 

### ISSUE THREAD

**Issue by skp-mel** [ClickHouse/power-bi-clickhouse#6] opened 2023-12-06 11:07 UTC
![image](https://github.com/ClickHouse/power-bi-clickhouse/assets/113598511/931f1603-0937-477f-9ac5-9d13752dd152)

Using the latest connector, I connected to a single table on a Direct Query mode. 

I noticed that any interactions between two visuals result in the error:
"OLE DB or ODBC error: [Expression.Error] We couldn't fold the expression to the data source. Please try a simpler expression."

In addition, if I set multiple items into the "Rows" of Matrix visuals, I get the same error every time when expanding / collapsing the "Rows". 

Could this issue be resolved?
I'm currently using a Power BI Desktop Report Server, and Clickhouse on-premise version.

**Comment by BentsiLeviav** [comment] 2024-02-04 12:02
Hi @skp-mel,

Could you please provide more information about the issue?

- Power BI version
- ODBC version
- ClickHouse version
- Data set sample
- Schema of the target table in ClickHouse

I tried it with my data and the matrix folding seems to work just fine (with 2 rows and aggregation as value).

**Comment by BentsiLeviav** [comment] 2024-03-10 14:42
I'm closing this for now as we couldn't reproduce the issue.
@skp-mel feel free to re-open in case you have a reproduceable example.

**Closed by BentsiLeviav** 2024-03-10 14:42 UTC
Labels: bug
