### ISSUE TITLE
[Expression.Error] We couldn't fold the expression to the data source"

### ISSUE THREAD

**Issue by bovinpa** [ClickHouse/power-bi-clickhouse#23] opened 2024-06-20 13:48 UTC
**Describe the bug**

**To Reproduce**
1. 
2. 
3.

**Expected behavior**

**Screenshots**

#### Environment
* PowerBI version:
* power-bi-clickhouse version:
* ClickHouse ODBC driver version
* Operating system:

**Additional context**

**Comment by BentsiLeviav** [comment] 2024-09-20 08:04
As no information was provided, and as this one is a duplicate of #24 I'm closing it.
In case it is not the same one and the error isn't caused by cross filters, feel free to reopen it with a proper explanation.

**Closed by BentsiLeviav** 2024-09-20 08:04 UTC
